### ISSUE TITLE
/config/config.ini exists error

### ISSUE THREAD

**Issue by hackmonker** [jkirkcaldy/plex-utills#33]
I am trying to run the docker container for the first time and it keeps giving me this error

```
services:
    plex-utills:
        image: jkirkcaldy/plex-utills
        container_name: plex-utills
        restart: unless-stopped
        volumes: 
            - /mnt:/mnt
            - /opt/plex-utills/config:/config
```

This is my compose

```
[PLEXSERVER]
PLEX_URL = http://plex:32400
TOKEN = jagpDD6WwrdzxXpno6CC
# This should match the library title seen in Plex
FILMSLIBRARY = 4K Movies
3D_Library = 3D-Films
#Use the setup helper if you don't know what to use here.
PLEXPATH = /mnt/unionfs/Media/Movies/Movies-4K

# If using Docker, leave this as /films. No trailing slash.
MOUNTEDPATH = /mnt/unionfs/Media/Movies/Movies-4K

[SCHEDULES]
#enter the time of day you want the script to run
4k_poster_schedule = 23:00
3d_poster_schedule = 22:45
disney_schedule = 22:00
pixar_schedule = 22:10
hide_poster_schedule = 01:00

[DOWNLOADERS]
#Coming Soon
sonarrurl = "https://sonarrurl"
sonarrapi = "sonarapi"
radarrurl = "https://radarurl"
radarrapi = "radarrapi"

[OPTIONS]
# Enter either True or False only to turn on/off the features you wish to use.
#Create a backup of your posters before adding banners. This is global for 4k/HDR or 3D films
POSTER_BU = true

4k_hdr_posters = true
mini_4k = false
HDR_BANNER = TRUE

3D_posters = false
mini_3D = false

Disney = false
Pixar = false
hide_4k = false

#Set this to true, if you would like your Plex Server to create an optimised HD version of your 4K films. This is not reccomended on low powered hardware
transcode = false

#Use ffmpeg to check for corrupted files. It will check files added in however many days you set below.
CHECK_FILES = false
#Set the number of days you want to go back and check, the longer you go back the longer the checks will take.
CHECK_FILES_HISTORY = 10
```
This is my config. 

what could be the reason?
